name: Publish prerelease
on:
  push:
    tags:
      - '*beta*'
      
jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      WEBCORD_BUILD: Devel
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Publish artifacts (x64)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish

    - name: Publish artifacts (arm64)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish -- -a arm64

    - name: Publish artifacts (armv7l)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish -- -a armv7l

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Publish artifacts (x64)
      env:
        WEBCORD_BUILD: Devel
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish

    - name: Publish artifacts (arm64)
      env:
        WEBCORD_BUILD: Devel
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish -- -a arm64

    - name: Publish artifacts (ia32)
      env:
        WEBCORD_BUILD: Devel
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish -- -a ia32

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Publish artifacts (x64)
      env:
        WEBCORD_BUILD: Devel
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish

    - name: Publish artifacts (arm64)
      env:
        WEBCORD_BUILD: Devel
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish -- -a arm64