name: Publish pre-release
on:
  push:
    tags: ['*beta*']

env:
  WEBCORD_BUILD: DEVEL

permissions:
  contents: write

jobs:
  publish:
    strategy:
      matrix:
        include:
          - name: Linux
            runner: ubuntu-latest
            arch: x64,arm64,armv7l
          - name: Windows
            runner: windows-latest
            arch: x64,arm64,ia32
          - name: macOS
            runner: macos-latest
            arch: x64,arm64 #,universal

    name: ${{ matrix.name }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: npm

      - name: Install dependencies (NPM)
        run: npm ci

      - name: TSC cache
        uses: actions/cache@v4
        with:
          key: tsc-release
          path: |
            app
            cache/tsc.json

      - name: Publish distributables (${{ matrix.arch}})
        uses: nick-fields/retry@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          retry_on: error
          max_attempts: ${{ matrix.name == 'Windows' && 6 || 3 }}
          timeout_minutes: ${{ matrix.name == 'Windows' && 15 || 10 }}
          command: npm run publish -- -a ${{ matrix.arch }}
