name: Publish release
on:
  push:
    tags-ignore: ['*beta*']

env:
  WEBCORD_BUILD: RELEASE

permissions:
  contents: write

jobs:
  publish:
    strategy:
      matrix:
        include:
          - name: Linux
            runner: ubuntu-20.04
            arch: x64,arm64,armv7l
          - name: Windows
            runner: windows-latest
            arch: x64,arm64,ia32
          - name: macOS
            runner: macos-latest
            arch: x64,arm64 #,universal

    name: ${{ matrix.name }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: TSC cache
        uses: actions/cache@v3
        with:
          key: tsc-${{ matrix.build }}
          path: |
            app
            cache/tsc.json

      - name: Publish distributables (${{ matrix.arch}})
        if: ${{ matrix.name != 'Windows' }}
        uses: nick-fields/retry@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          retry_on: error
          max_attempts: 3
          timeout_minutes: 10
          command: npm run publish -- -a ${{ matrix.arch }}

      - name: Publish distributables (${{ matrix.arch}}) (more retries)
        if: ${{ matrix.name == 'Windows' }}
        uses: nick-fields/retry@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          retry_on: error
          max_attempts: 6
          timeout_minutes: 15
          command: npm run publish -- -a ${{ matrix.arch }}
